//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://pys/")]
    [System.SerializableAttribute()]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sField;
        
        private int kField;
        
        private float fField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string s {
            get {
                return this.sField;
            }
            set {
                if ((object.ReferenceEquals(this.sField, value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int k {
            get {
                return this.kField;
            }
            set {
                if ((this.kField.Equals(value) != true)) {
                    this.kField = value;
                    this.RaisePropertyChanged("k");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float f {
            get {
                return this.fField;
            }
            set {
                if ((this.fField.Equals(value) != true)) {
                    this.fField = value;
                    this.RaisePropertyChanged("f");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pys/", ConfigurationName="ServiceReference1.SimplexSoap")]
    public interface SimplexSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (add) сообщения add не соответствует значению по умолчанию (Add).
        [System.ServiceModel.OperationContractAttribute(Action="http://pys/add", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.add1 Add(WindowsFormsApp1.ServiceReference1.add request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pys/add", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.add1> AddAsync(WindowsFormsApp1.ServiceReference1.add request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (concat) сообщения concat не соответствует значению по умолчанию (Concat).
        [System.ServiceModel.OperationContractAttribute(Action="http://pys/concat", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.concat1 Concat(WindowsFormsApp1.ServiceReference1.concat request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pys/concat", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.concat1> ConcatAsync(WindowsFormsApp1.ServiceReference1.concat request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (sum) сообщения sum не соответствует значению по умолчанию (Sum).
        [System.ServiceModel.OperationContractAttribute(Action="http://pys/sum", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.sum1 Sum(WindowsFormsApp1.ServiceReference1.sum request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pys/sum", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.sum1> SumAsync(WindowsFormsApp1.ServiceReference1.sum request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (adds) сообщения adds не соответствует значению по умолчанию (Adds).
        [System.ServiceModel.OperationContractAttribute(Action="http://pys/adds", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.adds1 Adds(WindowsFormsApp1.ServiceReference1.adds request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pys/adds", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.adds1> AddsAsync(WindowsFormsApp1.ServiceReference1.adds request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://pys/", IsWrapped=true)]
    public partial class add {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pys/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pys/", Order=1)]
        public int y;
        
        public add() {
        }
        
        public add(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://pys/", IsWrapped=true)]
    public partial class add1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pys/", Order=0)]
        public int addResult;
        
        public add1() {
        }
        
        public add1(int addResult) {
            this.addResult = addResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="concat", WrapperNamespace="http://pys/", IsWrapped=true)]
    public partial class concat {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pys/", Order=0)]
        public string s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pys/", Order=1)]
        public double d;
        
        public concat() {
        }
        
        public concat(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="concatResponse", WrapperNamespace="http://pys/", IsWrapped=true)]
    public partial class concat1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pys/", Order=0)]
        public string concatResult;
        
        public concat1() {
        }
        
        public concat1(string concatResult) {
            this.concatResult = concatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sum", WrapperNamespace="http://pys/", IsWrapped=true)]
    public partial class sum {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pys/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.A msu1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pys/", Order=1)]
        public WindowsFormsApp1.ServiceReference1.A msu2;
        
        public sum() {
        }
        
        public sum(WindowsFormsApp1.ServiceReference1.A msu1, WindowsFormsApp1.ServiceReference1.A msu2) {
            this.msu1 = msu1;
            this.msu2 = msu2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumResponse", WrapperNamespace="http://pys/", IsWrapped=true)]
    public partial class sum1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pys/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.A sumResult;
        
        public sum1() {
        }
        
        public sum1(WindowsFormsApp1.ServiceReference1.A sumResult) {
            this.sumResult = sumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="adds", WrapperNamespace="http://pys/", IsWrapped=true)]
    public partial class adds {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pys/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pys/", Order=1)]
        public int y;
        
        public adds() {
        }
        
        public adds(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addsResponse", WrapperNamespace="http://pys/", IsWrapped=true)]
    public partial class adds1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pys/", Order=0)]
        public int addsResult;
        
        public adds1() {
        }
        
        public adds1(int addsResult) {
            this.addsResult = addsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplexSoapChannel : WindowsFormsApp1.ServiceReference1.SimplexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.SimplexSoap>, WindowsFormsApp1.ServiceReference1.SimplexSoap {
        
        public SimplexSoapClient() {
        }
        
        public SimplexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.add1 WindowsFormsApp1.ServiceReference1.SimplexSoap.Add(WindowsFormsApp1.ServiceReference1.add request) {
            return base.Channel.Add(request);
        }
        
        public int Add(int x, int y) {
            WindowsFormsApp1.ServiceReference1.add inValue = new WindowsFormsApp1.ServiceReference1.add();
            inValue.x = x;
            inValue.y = y;
            WindowsFormsApp1.ServiceReference1.add1 retVal = ((WindowsFormsApp1.ServiceReference1.SimplexSoap)(this)).Add(inValue);
            return retVal.addResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.add1> WindowsFormsApp1.ServiceReference1.SimplexSoap.AddAsync(WindowsFormsApp1.ServiceReference1.add request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.add1> AddAsync(int x, int y) {
            WindowsFormsApp1.ServiceReference1.add inValue = new WindowsFormsApp1.ServiceReference1.add();
            inValue.x = x;
            inValue.y = y;
            return ((WindowsFormsApp1.ServiceReference1.SimplexSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.concat1 WindowsFormsApp1.ServiceReference1.SimplexSoap.Concat(WindowsFormsApp1.ServiceReference1.concat request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            WindowsFormsApp1.ServiceReference1.concat inValue = new WindowsFormsApp1.ServiceReference1.concat();
            inValue.s = s;
            inValue.d = d;
            WindowsFormsApp1.ServiceReference1.concat1 retVal = ((WindowsFormsApp1.ServiceReference1.SimplexSoap)(this)).Concat(inValue);
            return retVal.concatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.concat1> WindowsFormsApp1.ServiceReference1.SimplexSoap.ConcatAsync(WindowsFormsApp1.ServiceReference1.concat request) {
            return base.Channel.ConcatAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.concat1> ConcatAsync(string s, double d) {
            WindowsFormsApp1.ServiceReference1.concat inValue = new WindowsFormsApp1.ServiceReference1.concat();
            inValue.s = s;
            inValue.d = d;
            return ((WindowsFormsApp1.ServiceReference1.SimplexSoap)(this)).ConcatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.sum1 WindowsFormsApp1.ServiceReference1.SimplexSoap.Sum(WindowsFormsApp1.ServiceReference1.sum request) {
            return base.Channel.Sum(request);
        }
        
        public WindowsFormsApp1.ServiceReference1.A Sum(WindowsFormsApp1.ServiceReference1.A msu1, WindowsFormsApp1.ServiceReference1.A msu2) {
            WindowsFormsApp1.ServiceReference1.sum inValue = new WindowsFormsApp1.ServiceReference1.sum();
            inValue.msu1 = msu1;
            inValue.msu2 = msu2;
            WindowsFormsApp1.ServiceReference1.sum1 retVal = ((WindowsFormsApp1.ServiceReference1.SimplexSoap)(this)).Sum(inValue);
            return retVal.sumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.sum1> WindowsFormsApp1.ServiceReference1.SimplexSoap.SumAsync(WindowsFormsApp1.ServiceReference1.sum request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.sum1> SumAsync(WindowsFormsApp1.ServiceReference1.A msu1, WindowsFormsApp1.ServiceReference1.A msu2) {
            WindowsFormsApp1.ServiceReference1.sum inValue = new WindowsFormsApp1.ServiceReference1.sum();
            inValue.msu1 = msu1;
            inValue.msu2 = msu2;
            return ((WindowsFormsApp1.ServiceReference1.SimplexSoap)(this)).SumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.adds1 WindowsFormsApp1.ServiceReference1.SimplexSoap.Adds(WindowsFormsApp1.ServiceReference1.adds request) {
            return base.Channel.Adds(request);
        }
        
        public int Adds(int x, int y) {
            WindowsFormsApp1.ServiceReference1.adds inValue = new WindowsFormsApp1.ServiceReference1.adds();
            inValue.x = x;
            inValue.y = y;
            WindowsFormsApp1.ServiceReference1.adds1 retVal = ((WindowsFormsApp1.ServiceReference1.SimplexSoap)(this)).Adds(inValue);
            return retVal.addsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.adds1> WindowsFormsApp1.ServiceReference1.SimplexSoap.AddsAsync(WindowsFormsApp1.ServiceReference1.adds request) {
            return base.Channel.AddsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.adds1> AddsAsync(int x, int y) {
            WindowsFormsApp1.ServiceReference1.adds inValue = new WindowsFormsApp1.ServiceReference1.adds();
            inValue.x = x;
            inValue.y = y;
            return ((WindowsFormsApp1.ServiceReference1.SimplexSoap)(this)).AddsAsync(inValue);
        }
    }
}
